version: '3'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    environment:
      - NEXUS_CONTEXT=nexus
    networks:
      - traefik_traefik
    ports:
      - 8081:8081
    volumes:
      - './nexus-data:/nexus-data'
    labels:
      - 'traefik.enable=true'
      - "traefik.http.routers.nexus.rule=Host(`localhost`) && PathPrefix(`/nexus`)"
      #- "traefik.http.routers.nexus.rule=Host(`nexus.localhost`)" #subdomain - remove NEXUS_CONTEXT
      - "traefik.port=8081"
networks:
  traefik_traefik:
    external: true
