version: '3.3'
services:
  sonarqube:
    image: sonarqube
    container_name: sonar
    environment:
      - sonar.web.context=/sonarqube #https://docs.sonarqube.org/latest/setup/install-server/ -- context
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonar.service=sonarqube-sonar"
      #- "traefik.http.routers.sonar.entrypoints=sonar"

      #- "traefik.http.routers.sonar.rule=Host(`sonar.localhost`)"  #works

      - "traefik.http.routers.sonar.rule=Host(`localhost`) && PathPrefix(`/sonarqube`)"
      #- "traefik.http.middlewares.sonar-stripprefix.stripprefix.prefixes=/sonarqube"
      #- "traefik.http.routers.sonar.middlewares=sonar-stripprefix"


      #- "traefik.http.middlewares.sonar-prefix.addprefix.prefix=/sonar"

      #- "traefik.http.routers.sonar.middlewares=sonar-replacepath"
      #- "traefik.http.middlewares.sonar-replacepath.replacepath.path=/sonar"
      #- "traefik.port=9000"
    networks:
      - traefik_traefik
    volumes:
      - './sonar-data/conf:/opt/sonarqube/conf'
      - './sonar-data/data:/opt/sonarqube/data'
      - './sonar-data/logs:/opt/sonarqube/logs'
      - './sonar-data/extensions:/opt/sonarqube/extensions'
networks:
  traefik_traefik:
    external: true
